
project_id = "dobtquebpcnzjisftcfh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.qr-redirect]
verify_jwt = false

[functions.lead-capture]
verify_jwt = false

[functions.validate-whatsapp]
verify_jwt = false

[functions.whatsapp-validation-callback]
verify_jwt = false

[functions.generate-event-report]
verify_jwt = true
