
project_id = "dobtquebpcnzjisftcfh"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
image_transformation = true

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true

[functions.whatsapp-validation-callback]
verify_jwt = false

[functions.validate-whatsapp]
verify_jwt = true

[functions.qr-redirect]
verify_jwt = false

[functions.lead-capture]
verify_jwt = false

[functions.send-webhook]
verify_jwt = true

[functions.database-export]
verify_jwt = true

[functions.database-import]
verify_jwt = true

[functions.generate-event-report]
verify_jwt = true

[functions.lead-status-callback]
verify_jwt = false

[functions.sync-leads]
verify_jwt = true
