
project_id = "iznfrkdsmbtynmifqcdd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_parameter_status = "off"

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
external_redirect_urls = ["https://localhost:3000/**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-webhook]
verify_jwt = false

[functions.message-delivery-webhook]
verify_jwt = false

[functions.message-delivery-proxy]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
inspector_port = 8083
