
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { loadSupabaseConfig } from '@/utils/supabaseClientUpdater';

// Função para obter cliente Supabase dinâmico
const getSupabaseClient = () => {
  // Tentar carregar configuração salva primeiro
  const savedConfig = loadSupabaseConfig();
  
  if (savedConfig && savedConfig.supabaseUrl && savedConfig.supabaseAnonKey) {
    console.log('[Supabase] Usando configuração dinâmica salva');
    return createClient<Database>(savedConfig.supabaseUrl, savedConfig.supabaseAnonKey, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  }
  
  // Fallback para configuração padrão (apenas se não houver configuração salva)
  console.log('[Supabase] Usando configuração padrão');
  const SUPABASE_URL = "https://dobtquebpcnzjisftcfh.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvYnRxdWVicGNuemppc2Z0Y2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzcyNTMsImV4cCI6MjA2NTE1MzI1M30.GvPd5cEdgmAZG-Jsch66mdX24QNosV12Tz-F1Af93_0";
  
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

// Export the dynamic client
export const supabase = getSupabaseClient();

// Função para recriar o cliente com novas configurações
export const recreateSupabaseClient = () => {
  const newClient = getSupabaseClient();
  // Substituir a instância exportada
  Object.assign(supabase, newClient);
  return newClient;
};
